runtime: python311
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2 # Change F1 to F2 (or higher if needed)

# Optional: You can also configure automatic scaling if you haven't already
# automatic_scaling:
#   min_instances: 0
#   max_instances: 5
#   target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
